name: Push Notebook to DSC-NCHU/Go-Tutorial
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Copy
          run: |
            mkdir tmp
            cp -R Notebook tmp
        - name: Push directory to another repository
          # You may pin to the exact commit or the version.
          # uses: cpina/github-action-push-to-another-repository@8e9bfb00e6687c3f5cbc272c09b9dd2c27c7720c
          uses: cpina/github-action-push-to-another-repository@v1.3
          env: 
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            # Source directory from the origin directory
            source-directory: tmp/Notebook
            # Name of the destination username/organization
            destination-github-username: DSC-NCHU
            # Destination repository
            destination-repository-name: Go-Tutorial
            # Email for the git commit
            commit-message: Sync from liao2000/Go-Practice 
            target-branch: main
