name: Push notebook to DSC-NCHU
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Clone from DSC-NCHU
          run: |
            git clone https://github.com/DSC-NCHU/Go-Tutorial.git
            rm -r Go-Tutorial/.git
        - name: Copy Notebooks to DSC-NCHU
          run: |
            cp -R Notebook Go-Tutorial
        - name: Push from liao2000 to DSC-NCHU
          run: |
            cd Go-Tutorial
            git init
            git config user.name  "CI"
            git config user.email "liao2000@github"
            git remote add secure-origin https://${{ secrets.API_TOKEN_GITHUB }}@github.com/DSC-NCHU/Go-Tutorial
            git add .
            git commit -m "automatically push form liao2000/Go-Practice.git"
            git push --force
