name: Push notebook to DSC-NCHU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: push
          run: |
            git init
            git config user.name  "Push-CI"
            git config user.email "pushCI@github.com"
            git remote add secure-origin https://${{ secrets.API_TOKEN_GITHUB }}@github.com/DSC-NCHU/Go-Tutorial
            git add Notebook
            git commit -m "automatically push form liao2000/Go-Practice.git"
            git push --force
